/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import static Main.MainUI.con;
import static Main.MainUI.rs;
import static Main.MainUI.stmt;
import static Main.Post.con;
import static Main.Post.rs;
import static Main.Post.stmt;
import static Main.Resh.con;
import static Main.Resh.rs;
import static Main.Resh.stmt;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class PostLent extends javax.swing.JFrame {
static Connection con;
static Statement stmt;
static ResultSet rs;
int pos=1;
    /**
     * Creates new form ClientGroupLent
     */
    public PostLent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Таблица \"Постановления\"");

        jLabel2.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Номер ");

        jLabel3.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Дата ");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton1.setText("Первая");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton2.setText("Последняя");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton3.setText("Следующая");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton4.setText("Предыдущая");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton5.setText("Очистить");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton6.setText("Удалить");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton7.setText("Сохранить");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton9.setText("Отчёт(лента)");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jButton10.setText("Закрыть");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jTextField1.setText("jTextField1");

        jTextField2.setFont(new java.awt.Font("BenguiatGothicCTT", 0, 14)); // NOI18N
        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("jTextField3");

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setText("jTextField4");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setText("jTextField5");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setText("jTextField6");

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setText("jTextField7");

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setText("jTextField8");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Наименование");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Краткое содержание");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Срок действия");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Дата вступления в силу");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ответственный");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Наименование файла");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ссылка на сайт");

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setText("jTextField9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(284, 284, 284))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jTextField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(jTextField7))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField8)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            rs.first();
            String NUMBER=rs.getString("number");
        String DATA=rs.getString("date");
        String NAME=rs.getString("name");
        String MES=rs.getString("message");
        String SROK=rs.getString("srok");
        String DATEPOST =rs.getString("date_resh");
        String EMP =rs.getString("employee");
        String FILE=rs.getString("file");
        String SSULKA=rs.getString("ssulka");
    jTextField1.setText(NUMBER);
     jTextField2.setText(DATA);
     jTextField3.setText(NAME);
     jTextField4.setText(MES);
     jTextField5.setText(SROK);
     jTextField6.setText(DATEPOST);
     jTextField7.setText(EMP);
     jTextField8.setText(FILE);
     jTextField9.setText(SSULKA);
        } catch (SQLException ex) {
            Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            rs.last();
            String NUMBER=rs.getString("number");
        String DATA=rs.getString("date");
        String NAME=rs.getString("name");
        String MES=rs.getString("message");
        String SROK=rs.getString("srok");
        String DATEPOST =rs.getString("date_resh");
        String EMP =rs.getString("employee");
        String FILE=rs.getString("file");
        String SSULKA=rs.getString("ssulka");
    jTextField1.setText(NUMBER);
     jTextField2.setText(DATA);
     jTextField3.setText(NAME);
     jTextField4.setText(MES);
     jTextField5.setText(SROK);
     jTextField6.setText(DATEPOST);
     jTextField7.setText(EMP);
     jTextField8.setText(FILE);
     jTextField9.setText(SSULKA);
        } catch (SQLException ex) {
            Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex);
        }                // TODO add your handling code here:                // TODO add your handling code here:                // TODO add your handling code here:                // TODO add your handling code here:                // TODO add your handling code here:                // TODO add your handling code here:                // TODO add your handling code here:                // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (rs.next()) {
                String NUMBER=rs.getString("number");
        String DATA=rs.getString("date");
        String NAME=rs.getString("name");
        String MES=rs.getString("message");
        String SROK=rs.getString("srok");
        String DATEPOST =rs.getString("date_resh");
        String EMP =rs.getString("employee");
        String FILE=rs.getString("file");
        String SSULKA=rs.getString("ssulka");
    jTextField1.setText(NUMBER);
     jTextField2.setText(DATA);
     jTextField3.setText(NAME);
     jTextField4.setText(MES);
     jTextField5.setText(SROK);
     jTextField6.setText(DATEPOST);
     jTextField7.setText(EMP);
     jTextField8.setText(FILE);
     jTextField9.setText(SSULKA);
            }
            else {
                rs.first();
                String NUMBER=rs.getString("number");
        String DATA=rs.getString("date");
        String NAME=rs.getString("name");
        String MES=rs.getString("message");
        String SROK=rs.getString("srok");
        String DATEPOST =rs.getString("date_resh");
        String EMP =rs.getString("employee");
        String FILE=rs.getString("file");
        String SSULKA=rs.getString("ssulka");
    jTextField1.setText(NUMBER);
     jTextField2.setText(DATA);
     jTextField3.setText(NAME);
     jTextField4.setText(MES);
     jTextField5.setText(SROK);
     jTextField6.setText(DATEPOST);
     jTextField7.setText(EMP);
     jTextField8.setText(FILE);
     jTextField9.setText(SSULKA);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex);
        }       // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (rs.previous()) {
                String NUMBER=rs.getString("number");
        String DATA=rs.getString("date");
        String NAME=rs.getString("name");
        String MES=rs.getString("message");
        String SROK=rs.getString("srok");
        String DATEPOST =rs.getString("date_resh");
        String EMP =rs.getString("employee");
        String FILE=rs.getString("file");
        String SSULKA=rs.getString("ssulka");
    jTextField1.setText(NUMBER);
     jTextField2.setText(DATA);
     jTextField3.setText(NAME);
     jTextField4.setText(MES);
     jTextField5.setText(SROK);
     jTextField6.setText(DATEPOST);
     jTextField7.setText(EMP);
     jTextField8.setText(FILE);
     jTextField9.setText(SSULKA);
            }
            else {
                rs.last();
                String NUMBER=rs.getString("number");
        String DATA=rs.getString("date");
        String NAME=rs.getString("name");
        String MES=rs.getString("message");
        String SROK=rs.getString("srok");
        String DATEPOST =rs.getString("date_resh");
        String EMP =rs.getString("employee");
        String FILE=rs.getString("file");
        String SSULKA=rs.getString("ssulka");
    jTextField1.setText(NUMBER);
     jTextField2.setText(DATA);
     jTextField3.setText(NAME);
     jTextField4.setText(MES);
     jTextField5.setText(SROK);
     jTextField6.setText(DATEPOST);
     jTextField7.setText(EMP);
     jTextField8.setText(FILE);
     jTextField9.setText(SSULKA);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex);
        }            // TODO add your handling code here:            // TODO add your handling code here:            // TODO add your handling code here:            // TODO add your handling code here:            // TODO add your handling code here:            // TODO add your handling code here:            // TODO add your handling code here:            // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                  try { 
    rs.deleteRow();
   rs.first(); 
JOptionPane.showMessageDialog(null,"Удалено!"); 
} catch (SQLException ex) { 
Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex); 
JOptionPane.showMessageDialog(null,"Ошибка!"); 
}                  // TODO add your handling code here:                  // TODO add your handling code here:                  // TODO add your handling code here:                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                   try {
        Integer NUMBER=Integer.parseInt(jTextField1.getText());
        Date DATA=java.sql.Date.valueOf(jTextField2.getText());              
        String NAME=jTextField3.getText();
        String MES=jTextField4.getText();
        String EMP=jTextField7.getText();
        String FILE=jTextField8.getText();
        String SROK=jTextField5.getText();
        Date DATEPOST=java.sql.Date.valueOf(jTextField6.getText());
        String SSULKA=jTextField9.getText();
        
            PreparedStatement stmt1 = null;
            stmt1 = con.prepareStatement("INSERT INTO public.post (number,date,name,message,srok,date_post,employee,file,ssulka) VALUES (?,?,?,?,?,?,?,?,?)");
        stmt1.setInt(1, NUMBER);
            stmt1.setDate(2, (java.sql.Date) DATA);
        stmt1.setString(7, EMP);
        stmt1.setString(3, NAME);
        stmt1.setString(4, MES);
        stmt1.setString(8, FILE);
        stmt1.setString(5, SROK);
        stmt1.setDate(6, (java.sql.Date) DATEPOST);
        stmt1.setString(9, SSULKA);
        
       stmt1.executeUpdate();
   JOptionPane.showMessageDialog(null,"Сохранено!");
       stmt1.close(); 
        } catch (SQLException ex) {
            Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Ошибка!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
try {
    String sql="SELECT * FROM \"public\".\"post\"";
        con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/postgres", "postgres", "1");
        stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
        rs=stmt.executeQuery(sql);
        rs.next();
        
        String NUMBER=rs.getString("number");
        String DATA=rs.getString("date");
        String NAME=rs.getString("name");
        String MES=rs.getString("message");
        String SROK=rs.getString("srok");
        String DATEPOST =rs.getString("date_resh");
        String EMP =rs.getString("employee");
        String FILE=rs.getString("file");
        String SSULKA=rs.getString("ssulka");
    jTextField1.setText(NUMBER);
     jTextField2.setText(DATA);
     jTextField3.setText(NAME);
     jTextField4.setText(MES);
     jTextField5.setText(SROK);
     jTextField6.setText(DATEPOST);
     jTextField7.setText(EMP);
     jTextField8.setText(FILE);
     jTextField9.setText(SSULKA);
     
    } catch (SQLException ex) {
        Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex);
    }               // TODO add your handling code here:               // TODO add your handling code here:               // TODO add your handling code here:               // TODO add your handling code here:               // TODO add your handling code here:               // TODO add your handling code here:               // TODO add your handling code here:               // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
int rowno=1;
 try{
 ResultSetMetaData rsmd=rs.getMetaData();
 int colno=rsmd.getColumnCount();//Получаем колличество столбцов
 rs.first();
    while (rs.next()) rowno=rowno+1;//Получаем колличество строк
    System.out.println(rowno);
    rs.first();//Переходим на первую запись
    Document d=new Document();//Создаём отчёт
    PdfWriter.getInstance(d, new FileOutputStream("E:/report1.pdf"));
    //Создаём таблицу
    PdfPTable pt=new PdfPTable(colno);
    d.open();//Открываем отчёт  
    BaseFont bf1 = BaseFont.createFont("me/font/arialbd.ttf", "Cp1251", BaseFont.EMBEDDED); //подключаем файл жирного шрифта Arial, который поддерживает кириллицу
    BaseFont bf2 = BaseFont.createFont("me/font/arial.ttf", "Cp1251", BaseFont.EMBEDDED); //подключаем файл шрифта Arial, который поддерживает кириллицу
    Font bfont = new Font(bf1,12);
    Font font = new Font(bf2,12);
    Font sfont=new Font(bf2,6);
    
   Paragraph header=new Paragraph("Отчёт 'Постановления'", bfont);
    header.setAlignment(Element.ALIGN_CENTER);//Выравнивание
    d.add(header);
    for (int i=0; i<rowno; i++) {
       Paragraph blank=new Paragraph("Номер: "+rs.getString(2),bfont);
      d.add(blank);
      Paragraph blank1=new Paragraph("Дата: "+rs.getString(3),font);
      d.add(blank1);
      Paragraph blank2=new Paragraph("Наименование: "+rs.getString(4),font);
      d.add(blank2);
      Paragraph blank3=new Paragraph("Краткое содержание: "+rs.getString(5),font);
      d.add(blank3);
      Paragraph blank4=new Paragraph("Срок действия: "+rs.getString(6),font);
      d.add(blank4);
      Paragraph blank5=new Paragraph("Дата вступления в силу: "+rs.getString(7),font);
      d.add(blank5);
      Paragraph blank6=new Paragraph("Ответственный: "+rs.getString(8),font);
      d.add(blank6);
      Paragraph blank7=new Paragraph("Наименование файла: "+rs.getString(9),font);
      d.add(blank7);
      Paragraph blank8=new Paragraph("Ссылка на сайт: "+rs.getString(10),font);
      d.add(blank8);
      blank1.setFirstLineIndent(100);
      Paragraph blank9=new Paragraph("",font);
      d.add(blank9);
       rs.next();
    }
     d.add(pt);
    d.close();
  File f=new File("E:/report1.pdf");
   Desktop.getDesktop().open(f);
 }
catch (IOException ex) {} catch (DocumentException | SQLException ex) {
        Logger.getLogger(PostLent.class.getName()).log(Level.SEVERE, null, ex);
    }
    // TODO add your handling code here:          // TODO add your handling code here:
              // TODO add your handling code here:          // TODO add your handling code here:
    // TODO add your handling code here:          // TODO add your handling code here:
              // TODO add your handling code here:          // TODO add your handling code here:
    // TODO add your handling code here:          // TODO add your handling code here:
              // TODO add your handling code here:          // TODO add your handling code here:
    // TODO add your handling code here:          // TODO add your handling code here:
              // TODO add your handling code here:          // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostLent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostLent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostLent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostLent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostLent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables


}
